### ISSUE TITLE
Core sends data before receipt of server's Hello message

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/core-communication-lib#28]
A workaround is in place, but this caused major issues when the server became faster.  It also requires the server to use more resources (storing up messages to process) before the handshake is fully complete.

Typically these are the events published early in the session, cc3000-patch-version, and so on.

**Comment by m-mcgowan** [comment]
oooh! This may be why sometimes the faster photon doesn't appear online immediately even though it's breathing cyan, and the failure is intermittent, indicating a possible timing issue.

I'll extend the scope of the handshake function to wait for the server hello message before returning to calling code.

**Comment by dmiddlecamp** [comment]
The cloud tries to buffer / replay messages sent too early, but yeah it'd be awesome if we didn't have to! :)

**Comment by m-mcgowan** [comment]
Done!
